DROP TABLE IF EXISTS users_roles;

ALTER TABLE users ADD COLUMN role_id BIGINT NULL DEFAULT NULL;

ALTER TABLE users ADD CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT;