ALTER TABLE activities ALTER COLUMN employee_id DROP NOT NULL, ALTER COLUMN employee_id DROP DEFAULT;
ALTER TABLE activities ALTER COLUMN vacancy_id DROP NOT NULL, ALTER COLUMN vacancy_id DROP DEFAULT;

