ALTER TABLE users ADD COLUMN created_at TIMESTAMP;
ALTER TABLE users ALTER COLUMN created_at SET DEFAULT NOW();

ALTER TABLE users ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE users ALTER COLUMN updated_at SET DEFAULT NOW();

ALTER TABLE roles ADD COLUMN created_at TIMESTAMP;
ALTER TABLE roles ALTER COLUMN created_at SET DEFAULT NOW();

ALTER TABLE roles ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE roles ALTER COLUMN updated_at SET DEFAULT NOW();

ALTER TABLE privileges ADD COLUMN created_at TIMESTAMP;
ALTER TABLE privileges ALTER COLUMN created_at SET DEFAULT NOW();

ALTER TABLE privileges ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE privileges ALTER COLUMN updated_at SET DEFAULT NOW();
